### ISSUE TITLE
React.createElement: type is invalid -- expected a string or a class/function but got: undefined

### ISSUE THREAD

**Issue by shooftie** [ReactTraining/react-router#4477]
## Test Case
```
import React from 'react'
import {
  BrowserRouter as Router,
  Route,
  Link
} from 'react-router-dom'

const Child = ({ match }) => (
  <div>
    <h3>ID: {match.params.id}</h3>
  </div>
)

const ParamsExample = () => (
  <Router>
    <div>
      <h2>Accounts</h2>
      <ul>
        <li><Link to="/netflix">Netflix</Link></li>
        <li><Link to="/zillow-group">Zillow Group</Link></li>
        <li><Link to="/yahoo">Yahoo</Link></li>
        <li><Link to="/modus-create">Modus Create</Link></li>
      </ul>

      <Route path="/:id" component={Child}/>
    </div>
  </Router>
)

export default ParamsExample
```

## Steps to reproduce

Create a new app
`npm install -g create-react-app`
`create-react-app react-router-params`
`cd react-router-params/`

Install react router
`npm install react-router-dom@next`

Paste in example lifted directly from [docs](https://reacttraining.com/react-router/examples/url-params)

Run it
`npm start`

## Expected Behavior

See [docs](https://reacttraining.com/react-router/examples/url-params)

## Actual Behavior

    Warning: React.createElement: type is invalid -- expected a string (for built-in components)
    or a class/function (for composite components) but got: undefined. You likely forgot to
    export your component from the file it's defined in. Check the render method of
    `ParamsExample`.

**Comment by pshrmn** [comment]
I just tested this and it worked for me. You pasted the above code into `src/App.js`?

**Comment by hyeluri** [comment]
having same issue as shooftie

**Comment by pshrmn** [comment]
@shooftie  @hyeluri Can either of you determine which component is invalid? Or at least upload a repo with the non-working code and post a link here?

**Comment by mjackson** [comment]
I just ran the entire command sequence @shooftie described and cannot duplicate this error. Closing.

**Comment by shooftie** [comment]
Thanks for your speedy response.

I am tearing my hair out here. I have followed the process above as well and am still getting the same error. Give me a day and I'll get you a repo.

**Comment by shooftie** [comment]
OK... I've tracked it down. I confess the mistake is on my part in that I didn't follow my own instructions and instead of installing `react-router-dom@next`, I used the entry in my own project's package.json and installed `react-router@4.0.0-alpha.6`.

This was the _root_ of the problem.

@hyeluri , make sure that you are using the right react-router package. In the version that I am using (specifically 4.0.0-alpha.6) there is no such component as `<Route />`, instead it uses `<Match />`, which behaves, as far as I can work out, in the same way.

**Comment by nicolas-zozol** [comment]
I'm not sure it's appropriate - it is in Stack -, but I ran in this google search with this bug:

`<Route path="5-b-box-mutation" component={<BoxMutation/>}/>`

instead of 

`<Route path="5-b-box-mutation" component={BoxMutation}/>`

**Comment by rajkovukovic** [comment]
Same problem. My error was

`import {DataTable} from './data_table';`

instead of

`import DataTable from './data_table';`

**Comment by albertovilla** [comment]
I was having a similar issue and realised that I was not importing Router correctly.

I was using 
`import { BrowserRouter as Router, Route } from 'react-router'`
instead of:
`import { BrowserRouter as Router, Route } from 'react-router-dom'`

**Comment by paojie** [comment]
@rajkovukovic thanks for solving my problem.

**Comment by YouNoCanNoBB** [comment]
@albertovilla Tks a lot.

**Comment by ristinolla** [comment]
I had the similar and couldn't tell the difference at first. 

I was using
`import Link from 'react-router-dom'`
instead of
import { Link } from 'react-router-dom'

So importing the Link as named import fixed the problem. The Link is a named export in the 'react-router-dom' module. See this for indepth explanation: http://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import/36796281

**Comment by preethijayanthi** [comment]
i am having the error " Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `classname`." how to solve this error anyone pls help me

**Comment by l3lackcurtains** [comment]
I solved it by  changing
` import { Link } from 'react-router'`
to
`import { Link } from 'react-router-dom'`

**Comment by alonecoder1337** [comment]
I got the same problem. Follow this thread for explanation.

https://stackoverflow.com/questions/42813342/react-createelement-type-is-invalid-expected-a-string/43868528#43868528

**Comment by steviesama** [comment]
I actually got this problem when I went back to a parallel web service for login that I hadn't updated for a bit and it was still using = require() for modules, and I'd changed the main web service to use a transpiler addon for import, and using the require in that case resulted in this problem. Changed it all to import module from './sourcefile'; fixed it for me.

**Comment by Gruneau** [comment]
I had the same problem, solved by changing:
`import Route from 'react-router-dom';
`to
`import { Route } from 'react-router-dom';
`

**Comment by daryn-k** [comment]
How can I solve this problem sor server side rendering?

**Comment by luckskywalker** [comment]
Just add 'export' before your class declaration. Like this : 

> export class MyClass extends Component {
  render() {
    return (
            <h1> Hello </h1>
    );
  }
}

export default MyClass;

**Comment by zsid** [comment]
I had the same problem. I was using `"react-router-redux": "^4.0.8"` and it didn't work. When I changed it to `"react-router-redux": "next"` it was fine.

**Comment by BernardoS** [comment]
I'm having a similar issue. I setted a `BrowserSync` dev environment with `webpack` and it seens that the `BrowserRouter` is somewhat troublesome in the first load of the environment.

After a reload everything is fine, but still, awkward.

```javascript
import React from 'react'
import {render} from 'react-dom'
import {BrowserRouter as Router} from 'react-router-dom'

render(
  <Router>
    <div>hi!</div>
  </Router>,
  document.getElementById('root')
)

if ('serviceWorker' in navigator && process.env.NODE_ENV === 'production') {
  navigator.serviceWorker.register('js/sw.js')
    .then(({scope}) => console.log(`ServiceWorker registration successful, scope: ${scope}`))
    .catch((err) => console.log('ServiceWorker registration failed: ', err))
}
```

**Comment by ktSempire** [comment]
check your main.js , remove unwanted code...

**Comment by YutHelloWorld** [comment]
don't install react-router@4.0, just install react-router@3.*

**Comment by BernardoS** [comment]
That is my main.js @ktSempire .

Anyway, solved the problem. It was nothing with react-router itself. Was a problem with the integration o the webpack-dev-middleware and browser-sync

**Comment by Nate-Wilkins** [comment]
I also ran into this issue but I was using `Link` from `react-router` and not `react-router-dom`. Once I switched it worked fine.

**Comment by marcusjwhelan** [comment]
@zsid  why do you think this is?

**Comment by nicubarbaros** [comment]
In my case I forgot to export my component ))

**Comment by FuruholmAnton** [comment]
@BernardoS I am also using browser-sync. How did you solve it?

**Comment by BernardoS** [comment]
@FuruholmAnton, I actually stopped using browser-sync, but the problem was the interaction between de webpack-dev-middleware and my server itself. apparently when I called `compiler.watch`, somehow it fucked it up with the dev-middleware.

**Comment by duhaime** [comment]
The component that threw this error was using `import { Link } from 'react-router';` (from earlier v3 code). I resolved the error by updating that line to `import { Link } from 'react-router-dom';`

**Comment by muzaffaryousaf** [comment]
For me, i've changed 
`import React, {Component} from 'react'` to `import React, { Component } from 'react'`

**Comment by choelterati** [comment]
I was getting similar errors and started playing with import statements trying to fix it after reading through this (react-router v4). What solved it for me was restarting the webpack dev-server I was running off of after changing the import to reference 'react-router-dom' from 'react-router'. Changing the import reference did not fix it on its own.

**Comment by abimelex** [comment]
It's really hard to find what exactly causes this error. Any hint's for debugging this issue?

**Comment by steviesama** [comment]
@abimelex Typically there is a problem in callback hell where something isn't finishing allocation in time for it to render and perhaps isn't properly checked at run-time. If you believe you did that well enough, I don't know about anything else. It's always been some variation of what I described when it happens to me.

**Comment by avaneeshtripathi** [comment]
The issue is because of the way you import. React components class/function should be imported like this:
- import ComponentName from './path-to-component';
and not:
- import {ComponentName} from './path-to-component';

Change the way you are importing the component, if there is an error, you are doing import incorrectly.

**Comment by tusharf5** [comment]
Mine was I had export statement two times for the same class.

**Comment by steferr** [comment]
@ristinolla Freaking love you dude!

**Comment by suredo** [comment]
If you do use "default" on export then you should import without braces, else you should use braces.
"Default" is used to tell, that is the main class of your code.

**Comment by M1seRy** [comment]
Tried everything but still got this error, finally I buy a new macbook pro, it works fine here! = =

**Comment by iamthuypham** [comment]
I have the same issue but with a normal component, not anything with react-router. I believe the cause is something else. 
Fixed by change from `import {something} from '../folder` to `import something from '../folder'`

**Comment by xploreraj** [comment]
Agree with @suredo 's comment. I was importing a _non-default_ `class` without curly-braces.

**Comment by mort3za** [comment]
My case was:  
```
const Header = (
  <h1>Title</h1>
);  
```
instead of:
```
const Header = () => (
  <h1>Title</h1>
)
```

**Comment by jordan-realfoto** [comment]
I think the larger issue is that the error message is incredibly vague. Any reason why react or react-router can't do a better job of catching the actual error instead of just throwing up it's hands when the component doesn't give back exactly what it wants?

**Comment by timdorr** [comment]
It's when the `component` prop is not a component. Unfortunately, because of stateless functional components, answering that question ahead of time is actually fairly hard to do. It's really on React to provide a better error for `React.createElement`.

**Comment by xploreraj** [comment]
Same error as @rajkovukovic , and I broke my head even with obvious error. Broke my head over it.

**Comment by totymedli** [comment]
For me this happened because I was using a [react-router-config](https://www.npmjs.com/package/react-router-config) which doesn't support `render` prop. Thank God it worked with `component`.

Wrong: 
```
{
  path: '/stuff/featured',
  render: props => <Stuff tab={TABS.FEATURED}/>,
}
```

Right:
```
{
  path: '/stuff/featured',
  component: props => <Stuff tab={TABS.FEATURED}/>,
}
```

**Comment by stenmuchow** [comment]
i had an old implementation of react router redux... updated my deps and all worked... 

```
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.9",
    "react-scripts": "1.1.1",
    "redux-saga": "^0.16.0"
  },
```

**Comment by fizzvr** [comment]
@stenmuchow 100% confirmed, worked for me too. Fixed by simple upgrade a module 💯

**Comment by pleerock** [comment]
maintainers please take a note on this issue - it is closed, but it got too much attention from lot of people - it indicates that there still a problem. 

Maybe package will be able to provide a detailed error message since its a common error.

As I see people issues in wrong imports which is silly error and imho people should use better IDEs with auto-importing and import suggestions/corrections, but anyway.
