### ISSUE TITLE
react-router-redex throws warnings with react 15.5

### ISSUE THREAD

**Issue by patresi** [ReactTraining/react-router#4932]
## Version
react-router 3.0.3
react-router-redux 4.0.8

## Issue
The changes in react 15.5 regarding PropTypes and createClass make react-router-redux throw two warnings. 

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

```
Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

Will this issue be solved or is it something that will be addressed when react-router-redux 5 is released with support for react-router 4?

**Comment by simonkberg** [comment]
Sorry to nit, but these warnings do not stem from `react-router-redux` (current version living [here](https://github.com/reactjs/react-router-redux)), they are all from the [v3 code base](https://github.com/ReactTraining/react-router/tree/v3) of `react-router`.

**Comment by timdorr** [comment]
Should be fixed on master. I'll see about getting a release out soon.

**Comment by simonkberg** [comment]
@timdorr this issue is regarding RR3 (which also uses the now deprecated `createClass` call). 

If you accept PR's for the v3 branch I'd be happy to contribute.

**Comment by timdorr** [comment]
Yep, we do. I will take care of it now, though. It's not that hard to go through, luckily.

**Comment by patresi** [comment]
@simonkberg I noticed that the error was due to the react-router version that's why I mentioned it in the report 😉 

@timdorr thanks for the speedy response and fix 👍

**Comment by pinggod** [comment]
@timdorr I met the same warning with react-router@2.8.1, so will you update 2.x version?

**Comment by timdorr** [comment]
No, we're not maintaining the 2.x versions. Upgrade to 3.x, it's just 2.x without the deprecation warnings.

**Comment by ken4ward** [comment]
```
modules.js?hash=1a6be65…:10730Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.printWarning @ modules.js?hash=1a6be65…:10730warning @ modules.js?hash=1a6be65…:10754meteorInstall.node_modules.react-addons-test-utils.index.js @ modules.js?hash=1a6be65…:31950fileEvaluate @ modules-runtime.js?hash=2b888cb…:207require @ modules-runtime.js?hash=2b888cb…:130meteorInstall.node_modules.meteor.react-runtime.react-runtime.js @ react-runtime.js:38fileEvaluate @ modules-runtime.js?hash=2b888cb…:207require @ modules-runtime.js?hash=2b888cb…:130(anonymous function) @ react-runtime.js?hash=be87be9…:115(anonymous function) @ react-runtime.js?hash=be87be9…:127
modules.js?hash=1a6be65…:10730Warning: HomeLayout: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.printWarning @ modules.js?hash=1a6be65…:10730warning @ modules.js?hash=1a6be65…:10754ReactClass.createClass @ modules.js?hash=1a6be65…:8480meteorInstall.client.components.layouts.home.jsx @ home.jsx:1fileEvaluate @ modules-runtime.js?hash=2b888cb…:207require @ modules-runtime.js?hash=2b888cb…:130(anonymous function) @ app.js?hash=22e6ff3…:124
kadira_react-layout.js?hash=c418396…:76 Uncaught TypeError: React.render is not a function(anonymous function) @ kadira_react-layout.js?hash=c418396…:76(anonymous function) @ kadira_react-layout.js?hash=c418396…:90
```Just start using React today and getting this error.

**Comment by FoxxMD** [comment]
Is this change still waiting to get into the v3 branch?

**Comment by simonkberg** [comment]
@FoxxMD the fixes has been released https://github.com/ReactTraining/react-router/releases/tag/v3.0.4

**Comment by FoxxMD** [comment]
@simonkberg  thanks! I didn't see it on the release page but I didn't scroll down far enough :)

**Comment by kevinguard** [comment]
@simonkberg I upgraded to `3.0.4` and am still seeing these warnings.

**Comment by simonkberg** [comment]
@kevinguard are you sure they're coming from RR? could you post the full stack trace?

**Comment by Fabiantjoeaon** [comment]
I am also still seeing these warnings

**Comment by dmk23** [comment]
I just upgraded to `3.0.5`, seeing the warning but they are from a different package. I guess lots of modules out there still not brought into compliance
