### ISSUE TITLE
React.lazy makes Route's proptypes fail

### ISSUE THREAD

**Issue by jgoux** [ReactTraining/react-router#6420]
Hello,

The newly introduced React.lazy for easy code-splitting is making the `Route` component proptypes to fail with the warning : 
```
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
```

## Version

react-router-dom: 4.4.0-beta.4
react: 16.6.0

## Test Case
I took the official example from here : https://reactjs.org/docs/code-splitting.html#route-based-code-splitting

https://codesandbox.io/s/xp2nwl2qxw

**Comment by nfvs** [comment]
Same thing with `React.memo()`.

**Comment by timdorr** [comment]
Likely fixed by #6327 and/or #6417.

**Comment by shawyu** [comment]
Did you also upgrade `react-dom` to `16.6.0`? I had the same issues but [this tweet](https://twitter.com/dan_abramov/status/1055139862247063553) from @gaearon to a similar issue solved it for me.

**Comment by rnnyrk** [comment]
So how exactly can I fix this warning? I'd read the #6417  and #6327 issues and saw the PR was merged into the master branch. Currently I'm on version `4.3.1` of `react-router` but still seeing this warning in the console. Thanks in advance!

**Comment by timdorr** [comment]
Wait for a release :)

**Comment by tylerwray** [comment]
@rnnyrk I just did the following for now 🤷‍♂️ 

```jsx
const Home = React.lazy(() => import('./Home')

<Route exact path="/" component={props => <Home {...props} />} />
```

**Comment by jadbox** [comment]
@tylerwray The trick doesn't seem to work with Typescript since Lazy doesn't have proper typing and jsx elements must be explicitly defined as a jsx component.

**Comment by timdorr** [comment]
This was fixed in beta.5.

**Comment by frehner** [comment]
#6447 :)

**Comment by selbekk** [comment]
Ah, sorry!

**Comment by pierreferry** [comment]
> @rnnyrk I just did the following for now 🤷‍♂️
> 
> ```js-jsx
> const Home = React.lazy(() => import('./Home')
> 
> <Route exact path="/" component={props => <Home {...props} />} />
> ```

This trick does fix the error, but can have some side effect since it makes Home component re-render at every parent render. ( eg: if Home have componentDidMount )

**Comment by pshrmn** [comment]
@pierreferry if you go that path, the `render` prop would be better.

**Comment by wulucxy** [comment]
@pshrmn hey，when will you publish 4.4.0 version，this is a common problem。

**Comment by vtereshyn** [comment]
Any updates?

**Comment by semoal** [comment]
Same here, any updates?

**Comment by gunn4r** [comment]
Same. Interestingly enough though @pierreferry 's workaround doesn't work for me and I continue to get the same error.  ¯\_(ツ)_/¯

**Comment by willnew** [comment]
I resolve this warning by using [render](https://reacttraining.com/react-router/web/api/Route/render-func) `<Route exact path="/" render={() => <Home />} />`

**Comment by vtereshyn** [comment]
@willnew , as @pierreferry mentioned:
`This trick does fix the error, but can have some side effect since it makes Home component re-render at every parent render. ( eg: if Home have componentDidMount )`

**Comment by pierreferry** [comment]
@vtereshyn I believe this is different : 
- @willnew uses render prop
- @tylerwray uses component prop
I haven't tested render method yet :)
Another thing i haven't tested: using not-inline functions
```
const renderHome = () => <Home />;

<Route exact path="/" render={renderHome} />
```

**Comment by willnew** [comment]
@vtereshyn I made a small [Demo](https://codesandbox.io/s/1qk0w13m8j), you can test with it with `Paint flashing` option enabled on Chrome developer tool, the Home component didn't get re-rendered every time its parent's state change. so I think its a workaround, though it is a trick

**Comment by vtereshyn** [comment]
@willnew , oh, sorry, misunderstood.
Okay, but its really a trick, so, I will wait for new release from react-router.

**Comment by willnew** [comment]
@vtereshyn it's OK, I made a mistake that I didn't explain in detail in my first comment.
For others who worry about the case which @pierreferry mentioned, you can edit the demo code by entering 
`<Route exact path="/" render={props => <Home {...props} />} />` 
and 
`<Route exact path="/" component={props => <Home {...props} />} />`
to see the paint flashing zone

**Comment by sunstorymvp** [comment]
another option is to extend proptype definition for `Route` `component` prop (if not removed on build):
```js
// react-router-dom-fix.js
import PropTypes from 'prop-types';
import { Route } from 'react-router-dom';

// suppress prop-types warning on Route component when using with React.lazy
// until react-router-dom@4.4.0 or higher version released
/* eslint-disable react/forbid-foreign-prop-types */
Route.propTypes.component = PropTypes.oneOfType([
  Route.propTypes.component,
  PropTypes.object,
]);
/* eslint-enable react/forbid-foreign-prop-types */

```

should not have any side effects...

**Comment by HaiDang666** [comment]
I have the same in js code, but it not happen in ts.

**Comment by prakashtsi** [comment]
> another option is to extend proptype definition for `Route` `component` prop (if not removed on build):
> 
> ```js
> // react-router-dom-fix.js
> import PropTypes from 'prop-types';
> import { Route } from 'react-router-dom';
> 
> // suppress prop-types warning on Route component when using with React.lazy
> // until react-router-dom@4.4.0 or higher version released
> /* eslint-disable react/forbid-foreign-prop-types */
> Route.propTypes.component = PropTypes.oneOfType([
>   Route.propTypes.component,
>   PropTypes.object,
> ]);
> /* eslint-enable react/forbid-foreign-prop-types */
> ```
> 
> should not have any side effects...

This works for me. is it trustable @sunstorymvp ?

**Comment by sunstorymvp** [comment]
@prakashtsi works as expected. waiting for new release which is compatible with React.lazy to get rid of this code

**Comment by aramvr** [comment]
I just fixed it with updating `react-dom` to `16.6.3`. 
So before this the `react` version for my project is `16.6.3` and the `react-dom` version is `16.4.1`. So I updated `react-dom` too.
