### ISSUE TITLE
[React.memo] Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`

### ISSUE THREAD

**Issue by Albert-Gao** [ReactTraining/react-router#6471]
```json
  "dependencies": {
    "react": "^16.7.0-alpha1",
    "react-dom": "^16.7.0-alpha1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1"
  },
```

How to reproduce:

1. create-react-app try
2. edit the App.js to the following:
```javascript
import React, {memo} from "react";

import { BrowserRouter, Route } from "react-router-dom";

const Test = memo(() => <div>Quick Test</div>);

function App() {
  return (
    <BrowserRouter>
      <Route path="*" component={Test} />
    </BrowserRouter>
  );
}

export default App;
```
3. yarn start, rendering works fine!

4. check the console:
> index.js:1452 Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
    in Route (at App.js:10)
    in App (at src/index.js:7)

I fired this issue at https://github.com/mobxjs/mobx-react-lite/issues/12 as well.

**Comment by timdorr** [comment]
This is fixed in 4.4. You can use the beta or wait for a final release.

**Comment by FredyC** [comment]
@timdorr I am curious. How is it actually fixed? I mean the prop types validator is still using `react-is` underneath which is being patched in [this fresh new PR](https://github.com/facebook/react/pull/14219/). I am either missing something here or you might have misunderstood the issue at hand? :)

**Comment by vensa-albertgao** [comment]
Found the PR, after landing, the issue shall resolved, https://github.com/ReactTraining/react-router/pull/6447

**Comment by FredyC** [comment]
@vensa-albertgao I wouldn't be so sure about that. There is still pending PR for `react-is` for handling `React.memo`. So if the PR #6447 gets merged now, it won't solve this particular issue for sure.

**Comment by Albert-Gao** [comment]
@FredyC haha, yes, exactly. Forgot that, yes, even this PR land, we need the actual fix land on react-is. But wait, how could this react router PR knows which version to bump... If react-is has not been fixed, the final version number is not there, yet, right...?

**Comment by frehner** [comment]
From what I can tell, the bump in #6447 will fix this issue for memo. 

The PR linked to by @FredyC is for `prop-types` and not for `react-is`; the latest `react-is` already supports [validating memo as noted here in the source code](https://github.com/facebook/react/blob/769b1f270e1251d9dbdce0fcbd9e92e502d059b8/packages/shared/isValidElementType.js#L36).

At least, from what I'm seeing. I could be wrong, but that's my interpretation of things.

**Comment by alan345** [comment]
same here.
![image](https://user-images.githubusercontent.com/15246526/49663863-d4b14280-fa04-11e8-94dd-7c32bb256803.png)

I have removed node_module as advised https://github.com/ReactTraining/react-router/pull/6447#issuecomment-435190692 but no changes

**Comment by frehner** [comment]
#6447 was merged but hasn't been released yet, so you'll still get that error until there's a new release

**Comment by Maximization** [comment]
Any ETA on the new release?

**Comment by frehner** [comment]
@seifsg not sure, I’m not someone who can make a new one so you’ll have to ask those in charge

**Comment by pixelypants** [comment]
Keen to get a new release also, how can we help?

**Comment by VincentLanglet** [comment]
No new release since four months.
What is missing @mjackson ? Can we help ?

**Comment by muralikrishnana** [comment]
Try using <Route render ={()=> <Test/>} path="<your path>"/> rather than using the component prop.

**Comment by stack-wuh** [comment]
![image](https://user-images.githubusercontent.com/34117238/53718944-a3c39b00-3e97-11e9-937b-b2e3658c27bf.png)
i resolved it

**Comment by The-Code-Monkey** [comment]
@stack-wuh what have you actually done to resolve it a screenshot isnt really much help

**Comment by vadymrybak** [comment]
Not sure if it's relevant. But in my case I'm using react hooks with router. So in order to get rid of this message I used this code:

`return <React.Fragment>
             <Switch>
                <Route exact path='/orders' component={withRouter(Orders)}/>
                <Route path='/orders/:orderId' component={withRouter(Order)}/>
            </Switch>
        </React.Fragment>
`

basically adding **withRouter** removes the message

**Comment by PutziSan** [comment]
> basically adding withRouter removes the message

Good idea, but you should not use a [HOC inside the render function](https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method).

I can confirm that this workaround works for 4.3:

```jsx
import React, { lazy, Suspense } from "react";
import { Route, withRouter } from "react-router-dom";

const LazyComponent = withRouter(lazy(() => import("./YourComponent")));

export function App() {
  return (
    <Suspense fallback={<div>loading...</div>}>
      <Route component={LazyComponent} />
    </Suspense>
  );
}
```

**Comment by FredyC** [comment]
@PutziSan It feels fairly silly to wrap component into another HOC just because prop types check is failing :)

What about trying 4.4-beta instead? I had no problem with that so far.

**Comment by Multimo** [comment]
I believe the HOC example works because its returning a function as opposed to what ever React.Lazy returns. You can achieve the same effect by just declaring the component as a function inline.

```JS
import React, { lazy, Suspense } from "react";
import { Route, withRouter } from "react-router-dom";

const LazyComponent = lazy(() => import("./YourComponent"));

export function App() {
  return (
    <Suspense fallback={<div>loading...</div>}>
      <Route component={() => <LazyComponent />} />
    </Suspense>
  );
}
```

**Comment by luisnoresv** [comment]
This issue is fixed with the last versión of react-router-dom@5.0.0

**Comment by agustin107** [comment]
I've solved updating `react-router-dom@5.0.1` and `react-router@5.0.1`.

**Comment by gpbl** [comment]
We still have this issue and we can't upgrade to v5 because it breaks our production build. Is there an alternative to fix this warning?

**Comment by sag1v** [comment]
As @gpbl mentioned, some of us can't upgrade to v4 / v5. 
So i wonder what is the perf penalty for:

instead of
```
<Route path='mypath' component={MyComponent} />
```

to do this
```
<Route path='mypath' component={props => <MyComponent {...props} />} />
```

**Comment by mqklin** [comment]
@sag1v you should use `render={props=> <MyComponent {...props}/>} `, not `component={props => <MyComponent {...props}/>}`

**Comment by sag1v** [comment]
Why not `component`?
Are you sure `render` exists on all versions? (3.2.0 for example)

**Comment by mqklin** [comment]
Hmm, not sure about `3.2.0`. 
I think `component={props => ...}` will cause big perf problems, because it will rerender your route component every time.

**Comment by sag1v** [comment]
> because it will rerender your route component every time
Everytime what, a route change?

**Comment by mqklin** [comment]
Every time your parent component (where you render `<Route...`) rerenders. I'm saying this because I had the same problem, that I replaced `component` with `render` and now it works OK.

**Comment by guilhermecatalan** [comment]
Sounds silly to say but... in some cases this is not a bug. One of your routes may be pointing to an empty file, throwing this error.
